#!/bin/bash
set -e

while [[ -n $1 ]]; do
  src="$1"
  dst="${1%.*}.opt.mp4"

  echo "$src"

  # https://superuser.com/a/424024/110699
  # https://superuser.com/a/1045060/110699
  # Modifications: Change bitrate from 5000k -> 2000k
  # Modifications: Remove minrate
  ffmpeg -y -i "$src" -c:v libx264 -b:v 1000k -maxrate 8000k -pass 1 -c:a aac -f mp4 /dev/null
  ffmpeg    -i "$src" -c:v libx264 -b:v 1000k -maxrate 8000k -pass 2 -c:a aac -movflags faststart "$dst"

  echo "-> $dst"

  shift
done
